version: '3'
services:
  db:
    restart: unless-stopped
  web:
    env_file: .env
    image: hakanensari/fixer
    logging:
      options:
        max-size: "50m"
        max-file: "10"
    restart: unless-stopped
  nginx-proxy:
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    logging:
      options:
        max-size: "50m"
        max-file: "10"
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - /etc/nginx/conf.d
      - ./limit_req.conf:/etc/nginx/conf.d/limit_req.conf:ro
      - certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html
      - vhost.d:/etc/nginx/vhost.d
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - html:/usr/share/nginx/html
      - vhost.d:/etc/nginx/vhost.d
volumes:
  certs:
  html:
  vhost.d:
